// import 'package:flutter/material.dart';
// import 'package:flex_color_scheme/flex_color_scheme.dart';
// import 'package:flex_seed_scheme/flex_seed_scheme.dart';
//
// // Made for FlexColorScheme version 7.0.1. Make sure you
// // use same or higher package version, but still same major version.
// // If you use a lower version, some properties may not be supported.
// // In that case remove them after copying this theme to your app.
// // theme: FlexThemeData.light(
// theme: FlexThemeData.light(
// scheme: FlexScheme.blueWhale,
// surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
// blendLevel: 10,
// appBarStyle: FlexAppBarStyle.background,
// bottomAppBarElevation: 1.0,
// subThemesData: const FlexSubThemesData(
// blendOnLevel: 20,
// blendTextTheme: true,
// useM2StyleDividerInM3: true,
// thickBorderWidth: 2.0,
// elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
// elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
// outlinedButtonOutlineSchemeColor: SchemeColor.primary,
// toggleButtonsBorderSchemeColor: SchemeColor.primary,
// segmentedButtonSchemeColor: SchemeColor.primary,
// segmentedButtonBorderSchemeColor: SchemeColor.primary,
// unselectedToggleIsColored: true,
// sliderValueTinted: true,
// inputDecoratorSchemeColor: SchemeColor.primary,
// inputDecoratorBackgroundAlpha: 15,
// inputDecoratorRadius: 10.0,
// inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
// chipRadius: 10.0,
// popupMenuRadius: 6.0,
// popupMenuElevation: 6.0,
// appBarScrolledUnderElevation: 8.0,
// drawerWidth: 280.0,
// drawerIndicatorSchemeColor: SchemeColor.primary,
// bottomNavigationBarMutedUnselectedLabel: false,
// bottomNavigationBarMutedUnselectedIcon: false,
// menuRadius: 6.0,
// menuElevation: 6.0,
// menuBarRadius: 0.0,
// menuBarElevation: 1.0,
// navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
// navigationBarMutedUnselectedLabel: false,
// navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
// navigationBarMutedUnselectedIcon: false,
// navigationBarIndicatorSchemeColor: SchemeColor.primary,
// navigationBarIndicatorOpacity: 1.00,
// navigationBarElevation: 2.0,
// navigationBarHeight: 70.0,
// navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
// navigationRailMutedUnselectedLabel: false,
// navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
// navigationRailMutedUnselectedIcon: false,
// navigationRailIndicatorSchemeColor: SchemeColor.primary,
// navigationRailIndicatorOpacity: 1.00,
// ),
// visualDensity: FlexColorScheme.comfortablePlatformDensity,
// useMaterial3: true,
// swapLegacyOnMaterial3: true,
// // To use the playground font, add GoogleFonts package and uncomment
// // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// darkTheme: FlexThemeData.dark(
// scheme: FlexScheme.blueWhale,
// surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
// blendLevel: 15,
// appBarStyle: FlexAppBarStyle.background,
// bottomAppBarElevation: 2.0,
// subThemesData: const FlexSubThemesData(
// blendOnLevel: 40,
// blendTextTheme: true,
// useM2StyleDividerInM3: true,
// thickBorderWidth: 2.0,
// elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
// elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
// outlinedButtonOutlineSchemeColor: SchemeColor.primary,
// toggleButtonsBorderSchemeColor: SchemeColor.primary,
// segmentedButtonSchemeColor: SchemeColor.primary,
// segmentedButtonBorderSchemeColor: SchemeColor.primary,
// unselectedToggleIsColored: true,
// sliderValueTinted: true,
// inputDecoratorSchemeColor: SchemeColor.primary,
// inputDecoratorBackgroundAlpha: 22,
// inputDecoratorRadius: 10.0,
// chipRadius: 10.0,
// popupMenuRadius: 6.0,
// popupMenuElevation: 6.0,
// drawerWidth: 280.0,
// drawerIndicatorSchemeColor: SchemeColor.primary,
// bottomNavigationBarMutedUnselectedLabel: false,
// bottomNavigationBarMutedUnselectedIcon: false,
// menuRadius: 6.0,
// menuElevation: 6.0,
// menuBarRadius: 0.0,
// menuBarElevation: 1.0,
// navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
// navigationBarMutedUnselectedLabel: false,
// navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
// navigationBarMutedUnselectedIcon: false,
// navigationBarIndicatorSchemeColor: SchemeColor.primary,
// navigationBarIndicatorOpacity: 1.00,
// navigationBarElevation: 2.0,
// navigationBarHeight: 70.0,
// navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
// navigationRailMutedUnselectedLabel: false,
// navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
// navigationRailMutedUnselectedIcon: false,
// navigationRailIndicatorSchemeColor: SchemeColor.primary,
// navigationRailIndicatorOpacity: 1.00,
// ),
// visualDensity: FlexColorScheme.comfortablePlatformDensity,
// useMaterial3: true,
// swapLegacyOnMaterial3: true,
// // To use the Playground font, add GoogleFonts package and uncomment
// // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// // If you do not have a themeMode switch, uncomment this line
// // to let the device system mode control the theme mode:
// // themeMode: ThemeMode.system,
//
// // Light and dark ColorSchemes made by FlexColorScheme v7.0.1.
// // These ColorScheme objects require Flutter 3.7 or later.
// const ColorScheme flexSchemeLight = ColorScheme(
// brightness: Brightness.light,
// primary: Color(0xff023047),
// onPrimary: Color(0xffeff2f4),
// primaryContainer: Color(0xff8edbce),
// onPrimaryContainer: Color(0xff192523),
// secondary: Color(0xfff07e24),
// onSecondary: Color(0xfffff8f1),
// secondaryContainer: Color(0xffffbf93),
// onSecondaryContainer: Color(0xff28211a),
// tertiary: Color(0xfff86541),
// onTertiary: Color(0xfffff6f4),
// tertiaryContainer: Color(0xffffad91),
// onTertiaryContainer: Color(0xff281e19),
// error: Color(0xffb00020),
// onError: Color(0xfffceff1),
// errorContainer: Color(0xfffcd8df),
// onErrorContainer: Color(0xff282526),
// background: Color(0xfff5f6f7),
// onBackground: Color(0xff131313),
// surface: Color(0xfffafafb),
// onSurface: Color(0xff090909),
// surfaceVariant: Color(0xffe4e6e7),
// onSurfaceVariant: Color(0xff111212),
// outline: Color(0xff868686),
// outlineVariant: Color(0xffd2d2d2),
// shadow: Color(0xff000000),
// scrim: Color(0xff000000),
// inverseSurface: Color(0xff101112),
// onInverseSurface: Color(0xfff5f5f5),
// inversePrimary: Color(0xff89adbf),
// surfaceTint: Color(0xff023047),
// );
//
// const ColorScheme flexSchemeDark = ColorScheme(
// brightness: Brightness.dark,
// primary: Color(0xff57859d),
// onPrimary: Color(0xffecf3f7),
// primaryContainer: Color(0xff2a9d8f),
// onPrimaryContainer: Color(0xffcdf1ed),
// secondary: Color(0xffed7f29),
// onSecondary: Color(0xfffff2e5),
// secondaryContainer: Color(0xff994600),
// onSecondaryContainer: Color(0xfff0d6c0),
// tertiary: Color(0xffff6e48),
// onTertiary: Color(0xfffff0ea),
// tertiaryContainer: Color(0xffa3290f),
// onTertiaryContainer: Color(0xfff3cdc5),
// error: Color(0xffcf6679),
// onError: Color(0xff28181a),
// errorContainer: Color(0xffb1384e),
// onErrorContainer: Color(0xfff8d2d9),
// background: Color(0xff151719),
// onBackground: Color(0xffdadada),
// surface: Color(0xff121414),
// onSurface: Color(0xffececec),
// surfaceVariant: Color(0xff343637),
// onSurfaceVariant: Color(0xffdfdfdf),
// outline: Color(0xff676767),
// outlineVariant: Color(0xff1b1b1b),
// shadow: Color(0xff000000),
// scrim: Color(0xff000000),
// inverseSurface: Color(0xfffafbfc),
// onInverseSurface: Color(0xff131313),
// inversePrimary: Color(0xff324650),
// surfaceTint: Color(0xff57859d),
// );