// // Made for FlexColorScheme version 7.0.1. Make sure you
// // use same or higher package version, but still same major version.
// // If you use a lower version, some properties may not be supported.
// // In that case remove them after copying this theme to your app.
import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
// theme: FlexThemeData.light(
// scheme: FlexScheme.tealM3,
// appBarStyle: FlexAppBarStyle.primary,
// appBarElevation: 4.0,
// bottomAppBarElevation: 8.0,
// tabBarStyle: FlexTabBarStyle.forAppBar,
// subThemesData: const FlexSubThemesData(
// interactionEffects: false,
// tintedDisabledControls: false,
// blendOnColors: false,
// useM2StyleDividerInM3: true,
// adaptiveRemoveElevationTint: FlexAdaptive.all(),
// adaptiveElevationShadowsBack: FlexAdaptive.all(),
// adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
// defaultRadius: 4.0,
// elevatedButtonSchemeColor: SchemeColor.onPrimary,
// elevatedButtonSecondarySchemeColor: SchemeColor.primary,
// inputDecoratorSchemeColor: SchemeColor.onSurface,
// inputDecoratorBackgroundAlpha: 13,
// inputDecoratorBorderSchemeColor: SchemeColor.primary,
// inputDecoratorUnfocusedBorderIsColored: false,
// fabUseShape: true,
// fabAlwaysCircular: true,
// chipSchemeColor: SchemeColor.primary,
// chipRadius: 20.0,
// popupMenuElevation: 8.0,
// tooltipRadius: 4,
// dialogElevation: 24.0,
// snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
// appBarScrolledUnderElevation: 4.0,
// tabBarIndicatorSize: TabBarIndicatorSize.tab,
// tabBarIndicatorWeight: 2,
// tabBarIndicatorTopRadius: 0,
// tabBarDividerColor: Color(0x00000000),
// drawerElevation: 16.0,
// drawerWidth: 304.0,
// bottomSheetElevation: 10.0,
// bottomSheetModalElevation: 20.0,
// bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
// bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
// bottomNavigationBarElevation: 8.0,
// menuElevation: 8.0,
// menuBarRadius: 0.0,
// menuBarElevation: 1.0,
// navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
// navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
// navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
// navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
// navigationBarIndicatorSchemeColor: SchemeColor.secondary,
// navigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
// navigationBarElevation: 0.0,
// navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
// navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
// navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
// navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
// navigationRailIndicatorSchemeColor: SchemeColor.secondary,
// ),
// visualDensity: FlexColorScheme.comfortablePlatformDensity,
// useMaterial3: true,
// // To use the playground font, add GoogleFonts package and uncomment
// // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// darkTheme: FlexThemeData.dark(
// scheme: FlexScheme.tealM3,
// appBarStyle: FlexAppBarStyle.material,
// appBarElevation: 4.0,
// bottomAppBarElevation: 8.0,
// tabBarStyle: FlexTabBarStyle.forAppBar,
// subThemesData: const FlexSubThemesData(
// interactionEffects: false,
// tintedDisabledControls: false,
// blendOnColors: false,
// useM2StyleDividerInM3: true,
// adaptiveElevationShadowsBack: FlexAdaptive.all(),
// adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
// defaultRadius: 4.0,
// elevatedButtonSchemeColor: SchemeColor.onPrimary,
// elevatedButtonSecondarySchemeColor: SchemeColor.primary,
// inputDecoratorSchemeColor: SchemeColor.onSurface,
// inputDecoratorBackgroundAlpha: 20,
// inputDecoratorBorderSchemeColor: SchemeColor.primary,
// inputDecoratorUnfocusedBorderIsColored: false,
// fabUseShape: true,
// fabAlwaysCircular: true,
// chipSchemeColor: SchemeColor.primary,
// chipRadius: 20.0,
// popupMenuElevation: 8.0,
// tooltipRadius: 4,
// dialogElevation: 24.0,
// snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
// appBarScrolledUnderElevation: 4.0,
// tabBarIndicatorSize: TabBarIndicatorSize.tab,
// tabBarIndicatorWeight: 2,
// tabBarIndicatorTopRadius: 0,
// tabBarDividerColor: Color(0x00000000),
// drawerElevation: 16.0,
// drawerWidth: 304.0,
// bottomSheetElevation: 10.0,
// bottomSheetModalElevation: 20.0,
// bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
// bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
// bottomNavigationBarElevation: 8.0,
// menuElevation: 8.0,
// menuBarRadius: 0.0,
// menuBarElevation: 1.0,
// navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
// navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
// navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
// navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
// navigationBarIndicatorSchemeColor: SchemeColor.secondary,
// navigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
// navigationBarElevation: 0.0,
// navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
// navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
// navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
// navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
// navigationRailIndicatorSchemeColor: SchemeColor.secondary,
// ),
// visualDensity: FlexColorScheme.comfortablePlatformDensity,
// useMaterial3: true,
// // To use the Playground font, add GoogleFonts package and uncomment
// // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// // If you do not have a themeMode switch, uncomment this line
// // to let the device system mode control the theme mode:
// // themeMode: ThemeMode.system,

// Light and dark ColorSchemes made by FlexColorScheme v7.0.1.
// These ColorScheme objects require Flutter 3.7 or later.
const ColorScheme homeventory = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff19647e),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xff0081a5),
  onPrimaryContainer: Color(0xffffffff),
  secondary: Color(0xfffeb716),
  onSecondary: Color(0xff000000),
  secondaryContainer: Color(0xffffba2a),
  onSecondaryContainer: Color(0xff000000),
  tertiary: Color(0xff006875),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffbff6ff),
  onTertiaryContainer: Color(0xff000000),
  error: Color(0xffba1a1a),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffffdad6),
  onErrorContainer: Color(0xff410002),
  background: Color(0xffffffff),
  onBackground: Color(0xff000000),
  surface: Color(0xffffffff),
  onSurface: Color(0xff000000),
  surfaceVariant: Color(0xffeeeeee),
  onSurfaceVariant: Color(0xff000000),
  outline: Color(0xff737373),
  outlineVariant: Color(0xffbfbfbf),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff121212),
  onInverseSurface: Color(0xffffffff),
  inversePrimary: Color(0xffa9dbed),
  surfaceTint: Color(0xff19647e),
);

const ColorScheme homeventoryDark = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xffffab00),
  onPrimary: Color(0xff000000),
  primaryContainer: Color(0xffff6e48),
  onPrimaryContainer: Color(0xffffffff),
  secondary: Color(0xff006878),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xff00325b),
  onSecondaryContainer: Color(0xffffffff),
  tertiary: Color(0xff57859d),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xff004e59),
  onTertiaryContainer: Color(0xffffffff),
  error: Color(0xffffb4ab),
  onError: Color(0xff690005),
  errorContainer: Color(0xff93000a),
  onErrorContainer: Color(0xffffb4ab),
  background: Color(0xff121212),
  onBackground: Color(0xffffffff),
  surface: Color(0xff121212),
  onSurface: Color(0xffffffff),
  surfaceVariant: Color(0xff323232),
  onSurfaceVariant: Color(0xffffffff),
  outline: Color(0xff8c8c8c),
  outlineVariant: Color(0xff404040),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xffffffff),
  onInverseSurface: Color(0xff000000),
  inversePrimary: Color(0xff705410),
  surfaceTint: Color(0xffffab00),
);
